#!/bin/bash

proj_1="$HOME/chezhian_files/applications/proj_1"
proj_2="$HOME/chezhian_files/applications/proj_2"
proj_1_mb="encompass sods oods fmp"
proj_2_mb="rods"
encompass="3333"
sods="4200"
oods="4333"
rods="4100"
fmp="5333"


start () {
    daemon --running --verbose --name=mbank
    RETVAL1=$?

    if [ $RETVAL1 = 0 ]
    then
        echo "Mountebank is already running"
    else
        echo -n "Starting Mountebank..."

        # Start daemon
        daemon --chdir="$HOME" --command "mb --allowInjection" --respawn --output=/var/log/mountebank/mb.log --name=mbank --verbose

        RETVAL=$?
        if [ $RETVAL = 0 ]
        then
            echo "done."
        else
            echo "failed. See error code for more information."
        fi
        return $RETVAL
    fi
}

stop () {
    # Stop daemon
    echo -n "Stopping Mountebank..."

    daemon --stop --name=mbank  --verbose
    RETVAL=$?

    if [ $RETVAL = 0 ]
    then
        echo "Done."
    else
        echo "Failed. See error code for more information."
    fi
    return $RETVAL
}

impost () {
    http post localhost:2525/imposters/ < "examples/$1.json"
}

delete () {
    http delete "localhost:2525/imposters/$1"
}

proj_1_up () {
    daemon --running --verbose --name=mbank
    RETVAL1=$?

    if [ $RETVAL1 != 0 ]
    then
        start
    fi

    cd $proj_1
    
    for imp in $proj_1_mb
    do
        
        eval delete \${$imp}
        impost $imp
    done
}

proj_2_up () {
    daemon --running --verbose --name=mbank
    RETVAL1=$?

    if [ $RETVAL1 != 0 ]
    then
        start
    fi

    cd $proj_2
    
    for imp in $proj_2_mb
    do
        eval delete \${$imp}
        impost $imp
    done
}

case "$1" in
    up)
        start
    ;;
    down)
        stop
    ;;
    proj_1)
        proj_1_up
    ;;
    proj_2)
        proj_2_up
    ;;
    *)
        echo $"Usage: mbank {up|down|proj_1|proj_2}"
        exit 3
    ;;
esac

exit $RETVAL
